FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM nginx:stable-alpine
# Remove configuração padrão
RUN rm /etc/nginx/conf.d/default.conf
# Copia seu arquivo customizado
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Copia o build para o Nginx
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
